eureka :
  enviroment : prd
  client :
    register-with-eureka : true
    fetch-registry : true
    healthcheck :
      enabled : true
    region : css
    availability-zones :
      css : sifangping,hexi
    serviceUrl :
      sifangping : http://172.29.63.11:9002/eureka/,http://172.29.63.12:9002/eureka/,http://172.29.63.13:9002/eureka/
      hexi : http://172.24.24.83:9002/eureka/,http://172.24.24.84:9002/eureka/,http://172.24.24.85:9002/eureka/
  server :
    enable-self-preservation : false
    eviction-interval-timer-in-ms: 10000

