eureka :
  enviroment : str
  client :
    register-with-eureka : true
    fetch-registry : true
    region : str
    availability-zones :
      uat : zone-uat
      str : zone-str
    serviceUrl :
      zoo-uat : http://172.16.49.78:9002/eureka/
      zoo-str : http://172.16.49.79:9002/eureka/
  server :
    enable-self-preservation : false