eureka :
  enviroment : sit
  client :
    register-with-eureka : true
    fetch-registry : true
    serviceUrl :
      defaultZone : http://172.16.49.77:9002/eureka/
  server :
    enable-self-preservation : false