spring :
  cloud :
    config :
      label : master
      server :
        git :
          clone-on-start : true
          uri : git@172.16.50.222:middleground/configcenter/cmpay-config-repo.git
          searchPaths : /{application}
eureka :
  instance :
    metadata-map :
      zone: zone-str
    lease-renewal-interval-in-seconds : 10
    lease-expiration-duration-in-seconds : 30
  client :
    healthcheck :
      enabled : true
    serviceUrl :
      defaultZone : http://172.16.49.79:9002/eureka/